[client]
showErrorDetails="full"
toolbarMode = "viewer"
showSidebarNavigation = false


[logger]
level = "error"
[theme]
base="dark"  # Options: "light", "dark"
primaryColor="#1f77b4"  # Hex color for primary elements
backgroundColor="#0e1117"  # Background color
secondaryBackgroundColor="#262730"  # Sidebar or secondary sections
textColor="#ffffff"  # Text color
font="sans serif"  # Options: "serif", "sans serif", or "monospace"









